version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
    volumes_from: [piwik]
    links:
      - piwik
  piwik:
    image: xdebug_piwik
    # build:
    #   context: .
    #   dockerfile: ./php/Dockerfile.piwik
    volumes:
      - ./var/log/php:/var/log/php
      # piwiki
      - /Users/jmpews/Downloads/piwik-2.15.0/piwik:/var/www/html/
    environment:
      # must not config it, unless you config the Debug Server
      # PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
      # your host ip
      XDEBUG_CONFIG: remote_host=10.0.246.147

