version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
    volumes_from: [fpm]
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./var/log/php:/var/log/php
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      # your host ip
      # XDEBUG_CONFIG: remote_host=x.x.x.x

