version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8088:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./var/log/php:/var/log/
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=192.168.2.114

